"""added foreign keys to order_products table

Revision ID: 141a5b966312
Revises: 77c0ac445269
Create Date: 2025-11-27 09:59:20.488114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '141a5b966312'
down_revision: Union[str, Sequence[str], None] = '77c0ac445269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products', sa.Column('order_id', sa.Integer(), nullable=False))
    op.add_column('orders_products', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_orders_products_order_id_orders'), 'orders_products', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('fk_orders_products_product_id_products'), 'orders_products', 'products', ['product_id'], ['id'])
    op.drop_column('orders_products', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(op.f('fk_orders_products_product_id_products'), 'orders_products', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_products_order_id_orders'), 'orders_products', type_='foreignkey')
    op.drop_column('orders_products', 'product_id')
    op.drop_column('orders_products', 'order_id')
    # ### end Alembic commands ###
