"""adds table customers

Revision ID: 1547d0137e73
Revises: 3ac1b2c77d3d
Create Date: 2025-11-25 10:01:53.238889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1547d0137e73'
down_revision: Union[str, Sequence[str], None] = '3ac1b2c77d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_categories_categoryname'), table_name='categories')
    op.create_unique_constraint(op.f('uq_categories_categoryname'), 'categories', ['categoryname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_categories_categoryname'), 'categories', type_='unique')
    op.create_index(op.f('uq_categories_categoryname'), 'categories', ['categoryname'], unique=True)
    # ### end Alembic commands ###
