"""added timestamps to customers table

Revision ID: b98af938c9dd
Revises: 659cd034f999
Create Date: 2025-11-27 08:39:16.155988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98af938c9dd'
down_revision: Union[str, Sequence[str], None] = '659cd034f999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    # ### end Alembic commands ###
